/* AUTH */
export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILUER";

export const SET_CURRENT_USER_START = "SET_CURRENT_USER_START";
export const SET_CURRENT_USER_SUCCESS = "SET_CURRENT_USER_SUCCESS";
export const SET_CURRENT_USER_FAILURE = "SET_CURRENT_USER_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";

/* TOPNAV */
export const TOGGLE_TOPNAV_DROPDOWN_MENU = "TOGGLE_TOPNAV_DROPDOWN_MENU";
export const CLOSE_TOPNAV_DROPDOWN_MENU = "CLOSE_TOPNAV_DROPDOWN_MENU";
export const CLICK_TOPNAV_MENU_LINK = "CLICK_TOPNAV_MENU_LINK";

export * from "./auth/actions";
export * from "./topnav/actions";