/* AUTH */
export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILUER";

export const SET_CURRENT_USER_START = "SET_CURRENT_USER_START";
export const SET_CURRENT_USER_SUCCESS = "SET_CURRENT_USER_SUCCESS";
export const SET_CURRENT_USER_FAILURE = "SET_CURRENT_USER_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";

/* TOPNAV */
export const TOGGLE_TOPNAV_DROPDOWN_MENU = "TOGGLE_TOPNAV_DROPDOWN_MENU";
export const CLOSE_TOPNAV_DROPDOWN_MENU = "CLOSE_TOPNAV_DROPDOWN_MENU";
export const CLICK_TOPNAV_MENU_LINK = "CLICK_TOPNAV_MENU_LINK";

/* ORDER PREVIEW */
export const TOGGLE_ORDER_PREVIEW_MODAL = "TOGGLE_ORDER_PREVIEW_MODAL";

/* CATEGORY */
export const ADD_CATEGORY_START = "ADD_CATEGORY_START";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILURE = "ADD_CATEGORY_FAILURE";

export const FETCH_ONE_CATEGORY_START = "FETCH_ONE_CATEGORY_START";
export const FETCH_ONE_CATEGORY_SUCCESS = "FETCH_ONE_CATEGORY_SUCCESS";
export const FETCH_ONE_CATEGORY_FAILURE = "FETCH_ONE_CATEGORY_FAILURE";

export const FETCH_ALL_CATEGORIES_START = "FETCH_ALL_CATEGORIES_START";
export const FETCH_ALL_CATEGORIES_SUCCESS = "FETCH_ALL_CATEGORIES_SUCCESS";
export const FETCH_ALL_CATEGORIES_FAILURE = "FETCH_ALL_CATEGORIES_FAILURE";

export const UPDATE_CATEGORY_START = "UPDATE_CATEGORY_START";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAILURE = "UPDATE_CATEGORY_FAILURE";

export const DELETE_CATEGORY_START = "DELETE_CATEGORY_START";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE";

/* CUSTOMER */
export const ADD_CUSTOMER_START = "ADD_CUSTOMER_START";
export const ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCCESS";
export const ADD_CUSTOMER_FAILURE = "ADD_CUSTOMER_FAILURE";

export const FETCH_ONE_CUSTOMER_START = "FETCH_ONE_CUSTOMER_START";
export const FETCH_ONE_CUSTOMER_SUCCESS = "FETCH_ONE_CUSTOMER_SUCCESS";
export const FETCH_ONE_CUSTOMER_FAILURE = "FETCH_ONE_CUSTOMER_FAILURE";

export const FETCH_ALL_CUSTOMERS_START = "FETCH_ALL_CUSTOMERS_START";
export const FETCH_ALL_CUSTOMERS_SUCCESS = "FETCH_ALL_CUSTOMERS_SUCCESS";
export const FETCH_ALL_CUSTOMERS_FAILURE = "FETCH_ALL_CUSTOMERS_FAILURE";

export const UPDATE_CUSTOMER_START = "UPDATE_CUSTOMER_START";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_FAILURE = "UPDATE_CUSTOMER_FAILURE";

export const DELETE_CUSTOMER_START = "DELETE_CUSTOMER_START";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_FAILURE = "DELETE_CUSTOMER_FAILURE";

/* PRODUCT */
export const ADD_PRODUCT_START = "ADD_PRODUCT_START";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";

export const FETCH_ONE_PRODUCT_START = "FETCH_ONE_PRODUCT_START";
export const FETCH_ONE_PRODUCT_SUCCESS = "FETCH_ONE_PRODUCT_SUCCESS";
export const FETCH_ONE_PRODUCT_FAILURE = "FETCH_ONE_PRODUCT_FAILURE";

export const FETCH_ALL_PRODUCTS_START = "FETCH_ALL_PRODUCTS_START";
export const FETCH_ALL_PRODUCTS_SUCCESS = "FETCH_ALL_PRODUCTS_SUCCESS";
export const FETCH_ALL_PRODUCTS_FAILURE = "FETCH_ALL_PRODUCTS_FAILURE";

export const UPDATE_PRODUCT_START = "UPDATE_PRODUCT_START";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";

export const DELETE_PRODUCT_START = "DELETE_PRODUCT_START";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

/* SUPPLIER */
export const ADD_SUPPLIER_START = "ADD_SUPPLIER_START";
export const ADD_SUPPLIER_SUCCESS = "ADD_SUPPLIER_SUCCESS";
export const ADD_SUPPLIER_FAILURE = "ADD_SUPPLIER_FAILURE";

export const FETCH_ONE_SUPPLIER_START = "FETCH_ONE_SUPPLIER_START";
export const FETCH_ONE_SUPPLIER_SUCCESS = "FETCH_ONE_SUPPLIER_SUCCESS";
export const FETCH_ONE_SUPPLIER_FAILURE = "FETCH_ONE_SUPPLIER_FAILURE";

export const FETCH_ALL_SUPPLIERS_START = "FETCH_ALL_SUPPLIERS_START";
export const FETCH_ALL_SUPPLIERS_SUCCESS = "FETCH_ALL_SUPPLIERS_SUCCESS";
export const FETCH_ALL_SUPPLIERS_FAILURE = "FETCH_ALL_SUPPLIERS_FAILURE";

export const UPDATE_SUPPLIER_START = "UPDATE_SUPPLIER_START";
export const UPDATE_SUPPLIER_SUCCESS = "UPDATE_SUPPLIER_SUCCESS";
export const UPDATE_SUPPLIER_FAILURE = "UPDATE_SUPPLIER_FAILURE";

export const DELETE_SUPPLIER_START = "DELETE_SUPPLIER_START";
export const DELETE_SUPPLIER_SUCCESS = "DELETE_SUPPLIER_SUCCESS";
export const DELETE_SUPPLIER_FAILURE = "DELETE_SUPPLIER_FAILURE";

/* ORDER */
export const ADD_ORDER_START = "ADD_ORDER_START";
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAILURE = "ADD_ORDER_FAILURE";

export const FETCH_ONE_ORDER_START = "FETCH_ONE_ORDER_START";
export const FETCH_ONE_ORDER_SUCCESS = "FETCH_ONE_ORDER_SUCCESS";
export const FETCH_ONE_ORDER_FAILURE = "FETCH_ONE_ORDER_FAILURE";

export const FETCH_ALL_ORDERS_START = "FETCH_ALL_ORDERS_START";
export const FETCH_ALL_ORDERS_SUCCESS = "FETCH_ALL_ORDERS_SUCCESS";
export const FETCH_ALL_ORDERS_FAILURE = "FETCH_ALL_ORDERS_FAILURE";

export const UPDATE_ORDER_START = "UPDATE_ORDER_START";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_FAILURE = "UPDATE_ORDER_FAILURE";

export const DELETE_ORDER_START = "DELETE_ORDER_START";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAILURE = "DELETE_ORDER_FAILURE";

/* STAFF */
export const ADD_STAFF_START = "ADD_STAFF_START";
export const ADD_STAFF_SUCCESS = "ADD_STAFF_SUCCESS";
export const ADD_STAFF_FAILURE = "ADD_STAFF_FAILURE";

export const FETCH_ONE_STAFF_START = "FETCH_ONE_STAFF_START";
export const FETCH_ONE_STAFF_SUCCESS = "FETCH_ONE_STAFF_SUCCESS";
export const FETCH_ONE_STAFF_FAILURE = "FETCH_ONE_STAFF_FAILURE";

export const FETCH_ALL_STAFF_START = "FETCH_ALL_STAFF_START";
export const FETCH_ALL_STAFF_SUCCESS = "FETCH_ALL_STAFF_SUCCESS";
export const FETCH_ALL_STAFF_FAILURE = "FETCH_ALL_STAFF_FAILURE";

export const UPDATE_STAFF_START = "UPDATE_STAFF_START";
export const UPDATE_STAFF_SUCCESS = "UPDATE_STAFF_SUCCESS";
export const UPDATE_STAFF_FAILURE = "UPDATE_STAFF_FAILURE";

export const DELETE_STAFF_START = "DELETE_STAFF_START";
export const DELETE_STAFF_SUCCESS = "DELETE_STAFF_SUCCESS";
export const DELETE_STAFF_FAILURE = "DELETE_STAFF_FAILURE";

export * from "./auth/actions";
export * from "./topnav/actions";
export * from "./order-preview/actions";
export * from "./category/actions";
export * from "./customer/actions";
export * from "./product/actions";
export * from "./supplier/actions";
export * from "./order/actions";
export * from "./staff/actions";